version: '3.8'

services:
  db:
    build:
      context: ./postgres
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  web:
    build: .
    container_name: flask_app
    command: flask run --host=0.0.0.0 --port=5000
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data:
