"""Initial migration.

Revision ID: 3ff22fadb2dc
Revises: 
Create Date: 2024-07-09 14:04:45.870447

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3ff22fadb2dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_department')
    op.drop_table('prerequisite')
    op.drop_table('campus')
    op.drop_table('account')
    op.drop_table('course')
    op.drop_table('instructor')
    op.drop_table('enrollment')
    op.drop_table('student_campus')
    op.drop_table('department')
    op.drop_table('transcript')
    op.drop_table('users')
    op.drop_table('student')
    op.drop_table('teaches')
    op.drop_table('advisor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advisor',
    sa.Column('advisorid', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('lastname', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('firstname', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('initials', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('jobtitle', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('advisorid', name='advisor_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('teaches',
    sa.Column('instructorid', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('courseprefix', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('semester', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['courseprefix', 'semester', 'year'], ['enrollment.courseprefix', 'enrollment.semester', 'enrollment.year'], name='teaches_courseprefix_semester_year_fkey'),
    sa.ForeignKeyConstraint(['instructorid'], ['instructor.instructorid'], name='teaches_instructorid_fkey'),
    sa.PrimaryKeyConstraint('instructorid', 'courseprefix', 'semester', 'year', name='teaches_pkey')
    )
    op.create_table('student',
    sa.Column('studentid', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('lastname', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('firstname', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('initials', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('dateofbirth', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.CHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('zipcode', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('major', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('advisorid', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['advisorid'], ['advisor.advisorid'], name='student_advisorid_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('studentid', name='student_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('users',
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), server_default=sa.text("'user'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('username', name='users_pkey')
    )
    op.create_table('transcript',
    sa.Column('studentid', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('totalcredits', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cumulativegpa', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=True),
    sa.Column('graduationstatus', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['studentid'], ['student.studentid'], name='transcript_studentid_fkey'),
    sa.PrimaryKeyConstraint('studentid', name='transcript_pkey')
    )
    op.create_table('department',
    sa.Column('departmentcode', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('departmentname', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('officelocation', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('chairpersonid', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chairpersonid'], ['instructor.instructorid'], name='department_chairpersonid_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('departmentcode', name='department_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('student_campus',
    sa.Column('studentid', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('campuscode', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['campuscode'], ['campus.campuscode'], name='student_campus_campuscode_fkey'),
    sa.ForeignKeyConstraint(['studentid'], ['student.studentid'], name='student_campus_studentid_fkey'),
    sa.PrimaryKeyConstraint('studentid', 'campuscode', name='student_campus_pkey')
    )
    op.create_table('enrollment',
    sa.Column('enrollmentid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('studentid', sa.VARCHAR(length=9), autoincrement=False, nullable=True),
    sa.Column('courseprefix', sa.VARCHAR(length=9), autoincrement=False, nullable=True),
    sa.Column('semester', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('grade', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['courseprefix'], ['course.courseprefix'], name='enrollment_courseprefix_fkey'),
    sa.ForeignKeyConstraint(['studentid'], ['student.studentid'], name='enrollment_studentid_fkey'),
    sa.PrimaryKeyConstraint('enrollmentid', name='enrollment_pkey'),
    sa.UniqueConstraint('courseprefix', 'semester', 'year', name='enrollment_courseprefix_semester_year_key')
    )
    op.create_table('instructor',
    sa.Column('instructorid', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('lastname', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('firstname', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('initials', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('instructorid', name='instructor_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('course',
    sa.Column('courseprefix', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('coursename', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('credithours', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('courseprefix', name='course_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('account',
    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('created_on', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='account_pkey'),
    sa.UniqueConstraint('email', name='account_email_key'),
    sa.UniqueConstraint('username', name='account_username_key')
    )
    op.create_table('campus',
    sa.Column('campuscode', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('campusname', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('zipcode', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('phonenumber', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('campuscode', name='campus_pkey')
    )
    op.create_table('prerequisite',
    sa.Column('courseprefix', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('prerequisiteprefix', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['courseprefix'], ['course.courseprefix'], name='prerequisite_courseprefix_fkey'),
    sa.ForeignKeyConstraint(['prerequisiteprefix'], ['course.courseprefix'], name='prerequisite_prerequisiteprefix_fkey'),
    sa.PrimaryKeyConstraint('courseprefix', 'prerequisiteprefix', name='prerequisite_pkey')
    )
    op.create_table('course_department',
    sa.Column('courseprefix', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('departmentcode', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['courseprefix'], ['course.courseprefix'], name='course_department_courseprefix_fkey'),
    sa.ForeignKeyConstraint(['departmentcode'], ['department.departmentcode'], name='course_department_departmentcode_fkey'),
    sa.PrimaryKeyConstraint('courseprefix', 'departmentcode', name='course_department_pkey')
    )
    # ### end Alembic commands ###
