# Use the official PostgreSQL 16 image as a base image
FROM postgres:16

# Set environment variables for the database
ENV POSTGRES_DB ssdDatabase
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD sql123

# Expose the PostgreSQL port
EXPOSE 5432
